name: Build and deploy JAR app to Azure Web App - sigemaBE2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Listar archivos target
        run: ls -l target/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_087B699F00A64533BD1756E4D8DE202E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DDB76CD609D34C1A891548B909AF0B54 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_837B32D5AB3844EE8C576DC8FF303287 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sigemaBE2'
          slot-name: 'Production'
          package: 'target/*.jar'
